kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:multicluster-mesh:agent
  namespace: {{ .ClusterName }}
rules:
- apiGroups: ["mesh.open-cluster-management.io"]
  resources: ["meshes", "meshdeployments", "meshfederations"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
