namespace: open-cluster-management

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml
- crd/mesh.open-cluster-management.io_meshes.yaml
- crd/mesh.open-cluster-management.io_meshdeployments.yaml
- crd/mesh.open-cluster-management.io_meshfederations.yaml

images:
- name: multicluster-mesh-addon
  newName: quay.io/open-cluster-management/multicluster-mesh-addon
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
